services:
  tlsfingerprint:
    build:
      context: ./.tlsfingerprint-server
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ./.tlsfingerprint-server/certs:/app/certs:ro
      - ./.tlsfingerprint-server/config.json:/app/config.json:ro
      - ./.tlsfingerprint-server/blockedIPs:/app/blockedIPs
    cap_add:
      - NET_ADMIN
      - NET_RAW
    healthcheck:
      test: ["CMD-SHELL", "wget -qO /dev/null --no-check-certificate https://localhost/api/clean && echo ok || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 12
      start_period: 60s
